### ISSUE TITLE
Cluster-wide flags

### ISSUE THREAD

**Issue by mrluc** [tompave/fun_with_flags#10]
This project uses pubsub now, but the issue of what to do if a node joins, how to tell if the local cache is good, etc, is one of those notoriously sticky wickets. 

If it used `Phoenix.Tracker`, it could have stronger guarantees about whether a feature 'should be' on or off cluster-wide, without worrying as much about keeping a local ets in sync itself -- at a cost of potentially increased latency in rolling out flag changes (just because of time required to be sure of consensus compared to straight pubsub w/o consensus, not because Tracker's not performant at running tons of feature flag lookups, which it would be). But tuning the tracker ttls downwards works really well, and a set of feature flags, even per-user ones, is the sort of thing that Tracker should be good at given its biggest use case.

That stronger consistency could also be helpful for other features, like occasionally persisting the feature flags, because you'd know you're persisting something consistent, not a local cache that might be out of sync.

**Comment by tompave** [comment]
Hey, hi, thank you for the suggestion.
I can see why adding a consensus-based system would be useful in some cases. First I'd like to be sure I understand the problem though.

> but the issue of what to do if a node joins, how to tell if the local cache is good, etc, is one of those notoriously sticky wickets.

I think I avoided the problem, to some extent, by forcing each node to build their local cache separately. If a new node joins its cache will be initially empty, and new flags will be cached when:

1. Something looks up a flag on that node (this could be during a HTTP request in Phoenix, for example)
2. The node received a pub-sub change notification for a flag and automatically reloads it, even if it wasn't cached already.

Also, the idea is that the local cache is to be _considered_ always good, and even if it isn't then the system will heal itself and be eventually consistent (the cache entries have a TTL that can be adjusted).
If a projects requires a stricter consistency model, it's still possible to disable the cache entirely and always look things up in Ecto or Redis. That's what other similar libs do and Redis performs reasonable well until you hit "webscale™️".

> at a cost of potentially increased latency in rolling out flag changes (just because of time required to be sure of consensus compared to straight pubsub w/o consensus, not because Tracker's not performant at running tons of feature flag lookups, which it would be). But tuning the tracker ttls downwards works really well (...)

That's good to know, thanks. The increased latency is not a concern. Or, rather, if it is then tuning the TTL is the same approach currently in use, so it should be fine.

> That stronger consistency could also be helpful for other features, like occasionally persisting the feature flags, because you'd know you're persisting something consistent, not a local cache that might be out of sync.

This is the bit I'm not sure about. By default all flag changes are always persisted, and the reason is that if the application crashes the flags need to be recovered. So flushing the flags to disk only occasionally would not be ideal.
Also, persisting a flag on a node uses a "read your writes" approach, so that after persisting a change the node will immediately read the flag back, update its cache, and emit the change pub-sub notification.

Another thing to keep in mind is that at the moment creating, updating and deleting a flag is idempotent, and you don't need to reconcile an update with the current data before saving the flag. The only issue, perhaps, is when multiple users are updating a flag or gate in different ways, but that's an isolated enough scenario that I'm not sure I would add the extra complexity needed to deal with it.

## on dependencies

There is also the fact that at the moment `Phoenix.PubSub` is an optional dependency, and using the `Tracker` would make it mandatory.

**Comment by tompave** [comment]
Since there haven't been further comments for one month now, and I don't think that this needs to be addressed, I'll close this issue.

Please feel free to comment if something new comes up, and I'll reopen it!
