### ISSUE TITLE
Request: Consider improving the documentation to be a little more straightforward

### ISSUE THREAD

**Issue by thiagomajesk** [tompave/fun_with_flags#101]
Hi! 

I guess I have a good use case to use this lib in my application but I found the documentation just overwhelmingly wordy. Also, I could not quite comprehend what configuration I need after reading the whole README file  - I still don't quite know how to configure this for my use-case. For example: Do I need to configure `cache_bust_notifications`, PubSub adapters, and whatnot to just use this with Phoenix and Ecto?).

One thing that I've missed is a Getting Started section that goes about installing and configuring the library. Right now, both the configuration and installation sections are almost at the end of the README file and a lot of things seem to be explained in parallel to each other. 

My suggestion is to extract the installation, configuration, and usage sections into a Get Started, struct and explain them in a little bit more focused fashion and let the miscellaneous part at the end (Web Dashboard, Origin, Caching, PubSub, etc). If possible, provide a complete installation/ configuration example for the simplest use-case, using the Ecto adapter in a Phoenix app, and then talk about using Redis and extensibility.

¹BTW: Why don't you use Ecto or something like Mnesia as the default configuration for persistence? I think that there's a lot of Elixir libs that over-rely on external dependencies to do this without actually needing it. I'm not quite sure why would Redisbe necessary for something like this.

**Comment by tompave** [comment]
Wow, that's a lot of criticism for an issue that asks for help with the package.

I suppose that things can always be improved, and there are some good points there about the readme. I think that a "getting started" guide is an especially good idea, and I'll add one when I have time. It doesn't seem screamingly urgent, as so far I don't have any other data point that supports the idea people find it hard to understand the documentation.

A TL;DR is that you are encouraged to configure `cache_bust_notifications`_if_ you're using the ETS cache and _if_ you're running your Phoenix app on multiple nodes (multiple instances of the Elixir app). If you're on a single node, or if yo don't use the ETS cache, there is no reason to bust the cache with notifications.

The package doesn't ship with a Mnesia adapter because it's not a good fit for the main use cases. A Mnesia persistence adapter can be easily implemented. Ecto is not the default because it requires multiple dependencies and it's more difficult to configure.

**Comment by thiagomajesk** [comment]
Hi @tompave, thanks for the response. 

> Wow, that's a lot of criticism for an issue that asks for help with the package.

I hope you understand that this issue is very honest unfiltered feedback from someone that just tried to use the package for the first time and had the issues I mentioned above - this is not meant to be criticism for the sake of criticism.

>  It doesn't seem screamingly urgent, as so far I don't have any other data point that supports the idea that people find it hard to understand the documentation

Urgent is very subjective indeed and by all means, do take what I reported with a grain of salt. But also do consider that it might be difficult for new people to adopt this package if this is not improved. 

Also, I don't think it would be a huge amount of work to structure the documentation a little better and provide better examples. If I had access to those examples/ configurations I could definitely help with that!

> The package doesn't ship with a Mnesia adapter because it's not a good fit for the main use cases

Really!? I wonder what Redis can do that Mnesia can't for this use-case.
