### ISSUE TITLE
Configure set of permitted flags

### ISSUE THREAD

**Issue by jotaviobiondo** [tompave/fun_with_flags#119]
First, congrats on the lib! I really like the features and it's being super useful :)

One thing that I was feeling the need, is to somehow configure a set of the available flags, something like this:

```elixir
config :fun_with_flags, 
  permitted_flags: [
    :feature_a,
    :feature_b,
    :feature_c,
  ]
```

I can see 2 advantages of having this:
1. When we are calling functions like `FunWithFlags.enabled?(:feature_a)` or `FunWithFlags.enable(:feature_a)`, we validate against the permitted flags. Useful to ensure there's not typo in the flag name, for example.
2. Listing the available flags in the UI even if they don't exist in the storage. This is because I always need to check the code before add them in through the UI, not a big deal, bit if they are already listed it would be a very nice thing :)

The 1st advantage could required a relatively big refactoring and for me is not that important. It's just a plus, I think.

The 2nd advantage I really like to have it, since it makes easier to work only with the UI. This could be implemented in 2 ways, I think:
1. Implementing in this repository, doing the logic inside `all_flag_names/0` and `all_flags/0`
2. Implementing in the https://github.com/tompave/fun_with_flags_ui repository.

I guess I could "override" the storage I'm using, creating my own adapter and doing these logics for the  `all_flag_names/0` and `all_flags/0`, but having this in the library can be easier for users :)

Do you think this is a valid feature to having in this library?

**Comment by tompave** [comment]
Hello, thank you for using the package and for the kind words. :-)

I can see how what you suggest would be useful, but I'm not sure about adding it to the package. I'm a big fan of simplicity, and what you're suggesting basically requires a block on the creation of flags: they can only be seeded from a known list, and once the known flags are created their gates can be toggled or cleared, but new flags should be created dynamically. I'm not saying it wouldn't be useful, but it's a significantly different UX mode and I'm not sure about adding it to the package.

Still, I think that some or all of it can be implemented without package changes.

> When we are calling functions like `FunWithFlags.enabled?(:feature_a)` or `FunWithFlags.enable(:feature_a)`, we validate against the permitted flags. Useful to ensure there's not typo in the flag name, for example.

That makes a lot of sense, but it could be achieved with your own wrapper (I haven't tried to run it or check if it compiles):

```elixir
defmodule MyAppFlags do
  @known_flags [
    :feature_a,
    :feature_b,
    :feature_c,
  ]

  defmodule UnknownFlagName do
    defexception [:message]
  end

  def enabled?(flag_name, for: for) do
    unless Enum.member?(@known_flags, flag_name) do
      raise UnknownFlagName, "flag #{flag_name} is not known"
    end
    FunWithFlags.enabled?(flag_name, for: for)
  end
end
```
(that's just an example. Making `@known_flags` a map instead of a list is probably faster to check if you have a lot of entries)

> Listing the available flags in the UI even if they don't exist in the storage. This is because I always need to check the code before add them in through the UI, not a big deal, bit if they are already listed it would be a very nice thing :)

This could be done with an initializer somewhere in your application. For example (I haven't tried to run it or check if it compiles):

```elixir
defmodule MyAppFlags do
  def bootstrap_known_flags do
    existing_flags := FunWithFlags.all_flag_names()
    @known_flags
    |> Enum.reject(&Enum.member?(existing_flags, &1)) # Exclude the ones that already exist.
    |> Enum.each(&FunWithFlags.disable/1) # Create the missing ones as disabled.
  end
end
```
Then you can invoke that function somewhere shortly after your application starts. And you might also want to add a step to clear any existing flag that doesn't appear in `@known_flags` anymore.

With those two things in place, all you need to do it make sure that your code doesn't invoke the `FunWithFlags` functions directly.

**Comment by jotaviobiondo** [comment]
Hey! Thanks for the response!

I get your point about simplicity, I'm a big fan of it too :). And you're right, the UX of the lib would change, so better to leave this for users who want to implement it and keep things in the lib simpler.

The first topic I achieved with a solution very similar to yours :)

The second I don't implemented, but your idea is very interesting! I will try it

Again, thanks for your time and for the lib!
