### ISSUE TITLE
[Question] Ensuring feature flags are in sync across dev environments

### ISSUE THREAD

**Issue by oliverswitzer** [tompave/fun_with_flags#125]
Hi,

Do you have any suggestions for ensuring that everyone's development / test environments are in sync when folks add new feature flags? We'd love some form of a version controlled config file that at the very least indicates the presence of flags, and even better, the desired flag state / gate / actor, so that each developer doesn't have to know what flags to set in their DB.

Cheers,
Oliver

**Comment by tompave** [comment]
Hey there, thank you for using the package and for asking this question!

The package doesn't support this sort of flag declaration file. I must admit that it sounds like a useful feature, and in principle I like the idea of a `flagfile` (just like a `Brewfile` for Homebrew and a `Gemfile` for Ruby). I'm just not certain about adding this sort of complexity to the package. For context, something similar was discussed in https://github.com/tompave/fun_with_flags/issues/119.

On to your question, I think that since it's only for dev/test then it should be easy. At least, there is no need to worry about race conditions when multiple application instances start (which I see as a source of complexity if I were to support this).

My suggestion is to have a module somewhere in your app where you programmatically define all your flags:

```elixir
defmodule LocalDevFlags do
  import FunWithFlags, only: [enable: 2, disable: 2, clear: 2]

  def reset() do
    clear :foo
    disable :foo
    enable :foo, for_actor: %MyApp.User{id: 42}
    enable :foo, for_actor: %MyApp.User{id: 43}

    clear :bar
    enable :bar
    disable :bar, for_group: "restricted_users"

    # More flag declarations...
  end
end
```

And then to call `LocalDevFlags.reset()` somewhere in your app initialization code.

This won't really prevent people from adding, deleting and changing flags, but it will bootstrap the set of flags in a standard way, automatically.

**Comment by oliverswitzer** [comment]
@tompave totally makes sense, that's actually the direction I just started working towards.

I'm assuming there currently is no way through the `FunWithFlags` module to clear all feature flags, other than going directly to my apps Repo?

**Comment by tompave** [comment]
You could do:
```elixir
FunWithFlags.all_flag_names()
|> elem(1)
|> Enum.each(&FunWithFlags.clear/1)
```
