### ISSUE TITLE
`disable/2` returns {:ok, true}

### ISSUE THREAD

**Issue by mbuffa** [tompave/fun_with_flags#169]
Hello there,
I just started using the lib, and I noticed that `disable/2` may return `{:ok, true}` while the typespec only mentions `{:ok, false}` or `{:error, any}`.

I'm not sure whether this is intended or not.

### Steps to reproduce

```
iex(1)> FunWithFlags.enable(:yolo, for_percentage_of: {:time, 0.5})
{:ok, true}
iex(2)> FunWithFlags.enabled?(:yolo)
true
iex(3)> FunWithFlags.disable(:yolo)
{:ok, true}
iex(4)> FunWithFlags.disable(:yolo)
{:ok, true}
iex(5)> FunWithFlags.disable(:yolo)
{:ok, false}
iex(6)> FunWithFlags.disable(:yolo)
{:ok, false}
iex(7)> FunWithFlags.disable(:yolo)
{:ok, true}
```

Also happens with a ratio of `0.7`

### Environment
On a M1 Pro (if that matters 😁 )

```
elixir 1.15.7-otp-26
erlang 26.1.2
```

`config.exs` (from DockYard howto)
```
config :fun_with_flags, :persistence,
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: MyApp.Repo

config :fun_with_flags, :cache_bust_notifications, enabled: false
```

**Comment by tompave** [comment]
Hi, thank you for using the library and for reporting the problem.

I see what's happening.
Yes, this is inconsistent behaviour that I hadn't noticed before. Good catch!

As you show in the snippet, it looks like this happens when a flag has a partially enabled percentage-of-time gate. Disabling a flag globally means disabling its boolean gate. When a flag is disabled, the function ends with a [verification step](https://github.com/tompave/fun_with_flags/blob/v1.11.0/lib/fun_with_flags.ex#L315) which returns the [current value of the flag](https://github.com/tompave/fun_with_flags/blob/v1.11.0/lib/fun_with_flags.ex#L514). That's meant to be a convenience to confirm to the caller that "yes, you disabled it successfully".

Because of [gate priority](https://github.com/tompave/fun_with_flags/tree/v1.11.0?tab=readme-ov-file#gate-priority-and-interactions), verifying a flag [checks first the boolean gate, and then the percentage gate](https://github.com/tompave/fun_with_flags/blob/v1.11.0/lib/fun_with_flags/flag.ex#L44) if the boolean gate is false. That occasionally results in the flag being enabled even thought the boolean gate is disabled.

That's actually expected behaviour. The type-spec is wrong.
