### ISSUE TITLE
Asymmetry between options accepted by `enable`/`disable` compared to `enabled?/2`

### ISSUE THREAD

**Issue by s3cur3** [tompave/fun_with_flags#175]
Hi there! First off, thank you for an outstanding library that's been useful for my team in production for a couple years now.

I have one minor feature request, which I'm happy to submit a PR for if it's something you'd like.

Right now, there's an important asymmetry between the options we most commonly use:

- `FunWithFlags.enable/2` and `disable/2` support `for_actor: some_actor` or `for_group: "my_group"`
- `FunWithFlags.enabled?/2`, however, only supports `for: some_actor`

I frequently make a mistake where I try to do something like:
- `FunWithFlags.enable(:some_flag, for: my_user)`, or
-  `FunWithFlags.enabled?(:some_flag, for_actor: my_user)`

I think the former of those might be caught at runtime (excellent), but the latter is not.

A couple possible solutions I can envision:

- Make `enabled?/2` accept the `:for_actor` keyword and treat it exactly like `:for`
- Make `enabled?/2` validate its keyword arguments (possibly via `Keyword.validate!/2`) and raise an error if you specify unsupported options

Thoughts?

Thanks for your time. ☺️

**Comment by tompave** [comment]
Hey there, thank you for using the library and for the kind words!

I see what you mean, but that's an intentional design choice. It's not strictly necessary, but I think it better communicates what those functions expect.

When _enabling_ or _disabling_ a flag, you must specify what you enable it _for_. Are you enabling it for an actor? Are you enabling it for a group? Consider this code:

```elixir
defimpl FunWithFlags.Actor, for: BitString do
  def id(str) do
    "string:#{str}"
  end
end

FunWithFlags.enable(:my_flag, for_actor: "foobar")
FunWithFlags.enable(:my_flag, for_group: "foobar")
```
Both of those `enable/2` calls are valid. Both are possible. And an application might have good reason to use strings as actors. And in fact:

```elixir
FunWithFlags.get_flag(:my_flag).gates
# [
#   %FunWithFlags.Gate{type: :actor, for: "string:foobar", enabled: true},
#   %FunWithFlags.Gate{type: :group, for: "foobar", enabled: true}
# ]
```

On the other hand, when _querying_ a flag the API must be generic. When calling `FunWithFlags.enabled?(:my_flag, for: thing)`, you don't know why the flag should be enabled for `thing`. Yes, `thing` must be an actor (implement that protocol) otherwise a runtime exception will be raised, but you don't know if the flag contains any actor gate that target that actor, or if you're checking some group gate.

If the flag turns out to be enabled because of some group gate, and the API used the `for_actor:` keyword, things might be confusing I think.

**Comment by tompave** [comment]
On this other point:

> I think the former of those might be caught at runtime (excellent), but the latter is not.
> A couple possible solutions I can envision:
> (...)
> * Make `enabled?/2` validate its keyword arguments (possibly via `Keyword.validate!/2`) and raise an error if you specify unsupported options

I think that it's already working as you describe. Both functions will fail if you call them with the wrong keyword:

```elixir
defimpl FunWithFlags.Actor, for: BitString do
  def id(str) do
    "string:#{str}"
  end
end

FunWithFlags.clear(:foo)
# :ok

FunWithFlags.enable(:foo, for_actor: "bar")
# {:ok, true}

FunWithFlags.enabled?(:foo, for: "bar")
# true

FunWithFlags.enable(:foo, for: "bar")
# ** (FunctionClauseError) no function clause matching in FunWithFlags.enable/2

FunWithFlags.enabled?(:foo, for_actor: "bar")
# ** (FunctionClauseError) no function clause matching in FunWithFlags.enabled?/2
```

**Comment by s3cur3** [comment]
Ah, you're right about the keyword argument validation. I could have sworn at some point I'd passed the wrong arguments and had it fail silently, but I might be wrong.

On the first point, about `enabled?/2` needing to be generic, I guess my thinking is: if I ask `FunWithFlags.enabled?(:my_flag, for_actor: my_user)`, I'm not asking if `:my_flag` was explicitly enabled for that particular user, but whether that actor should have access to the feature flag; that could be because the flag is enabled globally, because the actor belongs to a group that the flag's enabled for, or (in the rarest case, within our codebase at least) because there's a one-off rule for that particular actor.

**Comment by tompave** [comment]
I think we agree on that, but my conclusion is that a simple `for:` feels more natural.

**Comment by s3cur3** [comment]
Fair enough!
