### ISSUE TITLE
Compiler Warning that Repo is unavailable

### ISSUE THREAD

**Issue by coryc5** [tompave/fun_with_flags#26]
Hi and thanks for your work on this library.

I get compiler warnings when I first compile the code:

```
==> fun_with_flags
Compiling 20 files (.ex)
warning: function Demo.Repo.all/1 is undefined (module Demo.Repo is not available)
Found at 3 locations:
  lib/fun_with_flags/store/persistent/ecto.ex:23
  lib/fun_with_flags/store/persistent/ecto.ex:157
  lib/fun_with_flags/store/persistent/ecto.ex:166

warning: function Demo.Repo.delete_all/1 is undefined (module Demo.Repo is not available)
Found at 3 locations:
  lib/fun_with_flags/store/persistent/ecto.ex:92
  lib/fun_with_flags/store/persistent/ecto.ex:119
  lib/fun_with_flags/store/persistent/ecto.ex:144

warning: function Demo.Repo.insert/2 is undefined (module Demo.Repo is not available)
  lib/fun_with_flags/store/persistent/ecto.ex:193

warning: function Demo.Repo.one/1 is undefined (module Demo.Repo is not available)
  lib/fun_with_flags/store/persistent/ecto.ex:44

warning: function Demo.Repo.transaction/1 is undefined (module Demo.Repo is not available)
  lib/fun_with_flags/store/persistent/ecto.ex:42

warning: function Demo.Repo.update/2 is undefined (module Demo.Repo is not available)
  lib/fun_with_flags/store/persistent/ecto.ex:200
```

because it looks like this module attribute gets compiled before my app is actually ready (since it gets compiled after fun_with_flags):
https://github.com/tompave/fun_with_flags/blob/21c4712286651b135bc36b02f766af3365c80fa1/lib/fun_with_flags/store/persistent/ecto.ex#L12

Outside of the warning, it doesn't appear to cause any issues but I thought I would bring it up in case it was unknown.

**Comment by tompave** [comment]
Hi, thanks for the report.

Yes, I had noticed. It's on the todo list.
As you mentioned, this is just a warning but has no effect at runtime. It's also only printed when fun_with_flags is compiled, but it doesn't really get in the way of your own application's compilation.

As you suggested, this happens because `Demo.Repo` (the atom `:Elixir.Demo.Repo`) is set in the Mix config of fun_with_flags, but the module doesn't really exist until your own `demo` app is compiled too. At runtime, later, the module is there and things are fine.

I'll need to convert `@repo Config.ecto_repo()` to a normal function call.
I've been resistant to removing those module attributes because they reduce the amount of data copied in and out of ETS (where the apps'c config is), but I guess that the persistent storage is used quite rarely with caching.

**Comment by jc00ke** [comment]
I just started using `FWF`, great work! Saw these warnings, glad they're not a big issue.

**Comment by tompave** [comment]
Thanks @jc00ke ! :-)

Sorting this out never made it to the top of the todo list because FWF has proved to be very stable (knocking on wood) in production, and in practice this has never been an issue.

For context, referencing the Mix config while the FWF app is compile, to store it as a module attribute is a performance optimization. Fetching some config would normally require reading from the Mix app's ETS table, (copying data out of ETS is one of the expensive things on the BEAM) plus a few function calls to merge the data with some defaults and then fetching a nested value. By storing the values as module attributes makes the whole operation way less expensive and faster, which is important for things that get used often. (Example: [the store module](https://github.com/tompave/fun_with_flags/blob/v1.4.1/lib/fun_with_flags.ex#L30). You compare that with [how that value is retrieved](https://github.com/tompave/fun_with_flags/blob/v1.4.1/lib/fun_with_flags/config.ex#L36-L63)). When writing FWF I've done it for things that are usually set _once_ per application, and are not meant to change at runtime.

One of the intended goals of FWF is make it fast and as lightweight as possible, because its API is meant to be safe to use in tight loops. Removing an ETS lookup helps.

**Comment by tompave** [comment]
I have an old work-in-progress branch where I started to change (some of) these module attributes. I also have another (broken) work-in-progress branch for v2.0 where the config is completely changes to use an `init()` callback (like Ecto's, basically what the Elixir core team recommends these days).

An easier way to address this would be to use https://hex.pm/packages/fastglobal I suppose.

**Comment by jc00ke** [comment]
That makes sense, thanks for the explanation @tompave. Looks like `init()` is the best option but I assume that would take a lot of work.

**Comment by mindreader** [comment]
Is this also the reason why sometimes in order to detect a config change (changing my repo from one to another) I have to purposely go into _build/lib and delete the fun_with_flags compilation because my old repo is stuck in the code?

Looking at the source, it should be as simple as changing all of these `@repo.one()` into `Config.ecto_repo().one()` etc.  I will be happy to submit a pr if you agree that this will fix it.

**Comment by tompave** [comment]
I did some work to address some of these issues with https://github.com/tompave/fun_with_flags/pull/79. I left the Ecto repo out of that PR, but it's easy to address that too. You can see it here: https://github.com/tompave/fun_with_flags/pull/80.

If that gets merged, there is only one instance of compiled-in config left, but that last one is a bit more difficult to wrangle for performance reasons.

**Comment by tompave** [comment]
I've merged https://github.com/tompave/fun_with_flags/pull/80 and it will be in the next released version. So this should be fixed now.
