### ISSUE TITLE
GenServer FunWithFlags.Notifications.PhoenixPubSub terminating

### ISSUE THREAD

**Issue by robertpeacock22** [tompave/fun_with_flags#27]
This issue is cropping up randomly when trying to run our Phoenix server. Sometimes it fails hard, sometimes it works fine. It's unclear if this is an actual issue with `FunWithFlags`, or if it's a knock-on issue from something else, so please bear with me. Also, the issue appears to involve `Logger` to some extent.

`elixir: "~> 1.6"`

`Logger` config:
```
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]
```

`FunWithFlags` config:
```
config :fun_with_flags, :cache,
  enabled: true,
  ttl: 300

config :fun_with_flags, :persistence,
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: Planswell.Api.Repo

config :fun_with_flags, :cache_bust_notifications,
  enabled: true,
  adapter: FunWithFlags.Notifications.PhoenixPubSub,
  client: lanswell.Api.PubSub
```

Stack trace:
```
11:42:17.890 [error] GenServer FunWithFlags.Notifications.PhoenixPubSub terminating
** (RuntimeError) Tried to subscribe to Phoenix.PubSub process Planswell.Api.PubSub 5 times. Giving up.
    (fun_with_flags) lib/fun_with_flags/notifications/phoenix_pubsub.ex:83: FunWithFlags.Notifications.PhoenixPubSub.subscribe/1
    (fun_with_flags) lib/fun_with_flags/notifications/phoenix_pubsub.ex:117: FunWithFlags.Notifications.PhoenixPubSub.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:subscribe_retry, 6}
==> common

=ERROR REPORT==== 26-Mar-2018::11:42:18 ===
** Generic server 'Elixir.FunWithFlags.Notifications.PhoenixPubSub' terminating 
** Last message in was {subscribe_retry,2}
** When Server state == <<"FUUOChZ9VDiTI3sxNTIyLCA3ODkzNywgNjgyNzA5fQ">>
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',
      message =>
          <<"cannot use Logger, the :logger application is not running">>},
    [{'Elixir.Logger.Config','__data__',0,
         [{file,"lib/logger/config.ex"},{line,53}]},
     {'Elixir.Logger',bare_log,3,[{file,"lib/logger.ex"},{line,613}]},
     {'Elixir.FunWithFlags.Notifications.PhoenixPubSub',handle_info,2,
         [{file,"lib/fun_with_flags/notifications/phoenix_pubsub.ex"},
          {line,116}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

=INFO REPORT==== 26-Mar-2018::11:42:18 ===
    application: fun_with_flags
    exited: shutdown
    type: temporary
** (Mix) Could not start application api: {:not_running, :fun_with_flags}
```

**Comment by tompave** [comment]
Hey, hi,

thank you for using the library and for the report.

Judging from the line numbers in the stack trace, you're using a version `<= 0.11.0`. Can you check which one please? I suggest you update to `1.0.0`, as it's generally retro-compatible.

>     11:42:17.890 [error] GenServer FunWithFlags.Notifications.PhoenixPubSub terminating
>     ** (RuntimeError) Tried to subscribe to Phoenix.PubSub process Planswell.Api.PubSub 5 times. Giving up.
>         (fun_with_flags) lib/fun_with_flags/notifications/phoenix_pubsub.ex:83: FunWithFlags.Notifications.PhoenixPubSub.subscribe/1
>         (fun_with_flags) lib/fun_with_flags/notifications/phoenix_pubsub.ex:117: FunWithFlags.Notifications.PhoenixPubSub.handle_info/2
>         (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
>         (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
>         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
>     Last message: {:subscribe_retry, 6}

That suggests that your `Planswell.Api.PubSub` process is not running. FunWithFlags [will retry to connect](https://github.com/tompave/fun_with_flags/blob/v0.11.0/lib/fun_with_flags/notifications/phoenix_pubsub.ex#L90) 5 times with one second pauses between the attempts, then give up and raise the error you're seeing. This is a race condition on application startup, which seems consistent with what you describe: it happens only sometimes.

You can [have a look at the connection retry logic](https://github.com/tompave/fun_with_flags/blob/v0.11.0/lib/fun_with_flags/notifications/phoenix_pubsub.ex#L58-L77) and try to run it with `debug` log level, to check what happens when it retries to connect.

>     =ERROR REPORT==== 26-Mar-2018::11:42:18 ===
>     ** Generic server 'Elixir.FunWithFlags.Notifications.PhoenixPubSub' terminating 
>     ** Last message in was {subscribe_retry,2}
>     ** When Server state == <<"FUUOChZ9VDiTI3sxNTIyLCA3ODkzNywgNjgyNzA5fQ">>
>     ** Reason for termination == 
>     ** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',
>           message =>
>               <<"cannot use Logger, the :logger application is not running">>},

This is odd.
This message, specifically:

> `** Last message in was {subscribe_retry,2}`

suggests that it failed after one attempt, not five. As for the rest of the message, it says that the `:logger` process is not available yet. Again, this seems a race condition between processes on startup.

I'm just a bit confused because the two blocks of the stack trace don't seem to fit with each other. In other words, if "`Last message in was {subscribe_retry,2}`", then I'm not sure why it raises the error for the 5 failed attempts. If you manage to reproduce it consistently, I'd be curious to understand what's happening. Just to be sure, is it possible you've copied and pasted two different stack traces from two different failures?

Anyway, to solve the problem you can try to add this somewhere at the beginning of your application's startup:

```elixir
Application.ensure_started(:logger)
Application.ensure_started(:phoenix_pubsub)
```

Let me know if it helps!

**Comment by tompave** [comment]
It's also possible that something (something else?) is crashing your `:logger` application tree, and the logger error you're seeing happens because FunWithFlags tries to log something while the logger is restarting.

**Comment by tompave** [comment]
Closing as it's an old issue, reported with an old version of the library.
