### ISSUE TITLE
[RFC] Allow disabled gates for % of Actor

### ISSUE THREAD

**Issue by erikreedstrom** [tompave/fun_with_flags#32]
The docs specify the following:

> The percentage gates can only express an enabled state, as disabling something for a percentage of time or actors is logically equivalent to enabling it for the complementary percentage.

However, because actor gates override group gates, there is a hole in certain contexts. 

For instance, if we want to allow all members of a group to have access to a new feature, but limit that group to a subset of actors, this is currently not possible as the actor gate overrides. For this to work, one would have to enable the group, but disable a % of the actors.

An alternative strategy, albeit one with significant change, would be to evaluate _all_ flags, and only pass if all resolve `true`. The same override functionality as currently exists could be achieved by providing a `veto` flag on a given gate.

Perhaps we're simply missing something about the setup though, and this type of subset limiting already exists.

**Comment by tompave** [comment]
Hi, and thanks for opening the issue.

I'm not sure I fully understand the scenario you're describing. Could you expand on a few points please?

> because actor gates override group gates 

True.

> For instance, if we want to allow all members of a group to have access to a new feature, but limit that group to a subset of actors, this is currently not possible _as the actor gate overrides_ [emphasis added]. For this to work, one would have to enable the group, but disable a % of the actors.

I'm not sure what you mean by "as the actor gate overrides". Later you mention the %-of-actors gate, which is different from the actor gate. While actor gates override group gates, %-of-actor gates do not. In fact, %-of-X gates are only checked if no actor or group gate matches the current actor, and if no boolean gate is enabled.

If you want to combine a group gate with actor gates, i.e. only enable the flags for explicitly defined actors, then you should only use the actor gates and no group gate. Any actor that doesn't match any actor gate but matches the group gate will in fact see the flag as enabled.

If, on the other hand, you want to enable a flag for a percentage of the members of a group, then you're right that it's not directly supported with a single flag. This is by design, because it allows to keep the gate interaction logic relatively simple. A solution is to treat flags and gates as primitive building blocks and manage your own combination logic.

For example, you could have a "base" flag to check which actors are in the group, and then a "filter" flag to check if the current actor is in the enabled percentage:

```elixir
FunWithFlags.enable(:foobar_base, for_group: "beta_testers")
FunWithFlags.enable(:foobar_filter, for_percentage_of: {:actors, 0.5})

defmodule Foo do
  def foobar_enabled?(user) do
    FunWithFlags.enabled?(:foobar_base, for: user) &&
      FunWithFlags.enabled?(:foobar_filter, for: user)
  end
end
```

> An alternative strategy, albeit one with significant change, would be to evaluate _all_ flags, and only pass if all resolve `true`. The same override functionality as currently exists could be achieved by providing a `veto` flag on a given gate.

I'm not sure what you mean by "evaluate all flags", but I assume that you meant "gates". I'd be against this internal change I'm afraid, for two reasons:

1. While I think that the package has some solid integration tests, I'm not comfortable changing the internals to that extent at this point. It might be ok for a 2.0 release, but I don't think I have enough other new features lined up to justify that.
2. It would come at a performance cost. At the moment the gates are evaluated in a specific order so that the function can do as little work as possible. Evaluating all the gates all the time, even when not required, would make the calls a bit slower.

**Comment by erikreedstrom** [comment]
> evaluate all flags
Yeah, I meant gates. 😬

As for the Actor/% of Actor, that was confusion on my part. When I set the % gate and group gate, the flag resolved to true regardless of group membership. It appeared to match the precedence order with Actor overriding Group. Per your description, it was actually that the group didn’t match, so fell through and passed on the % of Actors. 

The scenario you provided with two flags seems too cumbersome, and there is no longer a representation of a feature with a single toggle. “As an actor do I have access to this feature, or do I _really_ have access?”

A disabled % gate would allow for this scenario under a single flag, no?

**Comment by tompave** [comment]
> When I set the % gate and group gate, the flag resolved to true regardless of group membership. It appeared to match the precedence order with Actor overriding Group. Per your description, it was actually that the group didn’t match, so fell through and passed on the % of Actors.

Yep, that sounds like the correct and expected behaviour. 👍 

> The scenario you provided with two flags seems too cumbersome, and there is no longer a representation of a feature with a single toggle.

Yes, it's true that it becomes more complex, but I would argue that the uncertainty about a flag state would be the same if the gates interacted in a more complex way within a single flag. Ultimately I think that making the gate interactions too complex would make the library less useful.

> “As an actor do I have access to this feature, or do I really have access?”

I think that you'd have the same doubt even with a single flag, if you could mix group and %-of-actors gates. The combination logic wouldn't be different, although actually you'd have no direct control over it.

> A disabled % gate would allow for this scenario under a single flag, no?

I don't think so. At the moment, % gates are only checked if no actor or group gate matches the current argument.

**Comment by erikreedstrom** [comment]
We decided to implement our own resolving logic -- cheers for making the lib accessible 🍺!

For what it's worth, I've posted the overlay. The main difference being the precedence of gates and how they combine. In the following, we define `Boolean > Actor > (Group & Percent)`.

The Boolean gate works as a master switch; requires the flag be expressly enabled for other gates to pass. Any Actor gate that is found will halt the evaluation and resolve the returned value. Provided Boolean and Actor passed, or Actor is ignored, Group and Percent are then evaluated together.

The same logic persists from the library: all Groups must pass to ensure conflicts resolve properly, and   % of Actor takes precedence over % of Time. Granted, the logic after Actor is subtractive rather than additive. If Group _and_ Percent are defined, both must evaluate to true for the flag to enable. This provides the gap in logic we were looking for.

## Alternative Resolution

This is called using the same API: `MoreWithFlags.enabled?(:some_flag, for: item)`.

```elixir
defmodule MoreWithFlags do
  @store FunWithFlags.Config.store_module()

  alias FunWithFlags.Flag
  alias FunWithFlags.Gate

  @spec enabled?(atom, Flag.options()) :: boolean
  def enabled?(flag_name, options \\ [])

  def enabled?(flag_name, []) when is_atom(flag_name) do
    case @store.lookup(flag_name) do
      {:ok, flag} -> flag_enabled?(flag)
      _ -> false
    end
  end

  def enabled?(flag_name, for: nil) do
    enabled?(flag_name)
  end

  def enabled?(flag_name, for: item) when is_atom(flag_name) do
    case @store.lookup(flag_name) do
      {:ok, flag} -> flag_enabled?(flag, for: item)
      _ -> false
    end
  end

  ## PRIVATE FUNCTIONS

  @spec flag_enabled?(Flag.t(), Flag.options()) :: boolean
  defp flag_enabled?(flag, options \\ [])

  defp flag_enabled?(%Flag{gates: []}, _), do: false

  defp flag_enabled?(%Flag{gates: gates, name: flag_name}, opts) do
    item = Keyword.get(opts, :for)
    gates = gates_by_type(gates)

    with {:flag_active, true} <- {:flag_active, check_boolean_gate(gates)},
         {:actor_override, :cont} <- {:actor_override, check_actor_gates(gates, item)},
         {:group_enabled, group_enabled} <- {:group_enabled, check_group_gates(gates, item)},
         {:pct_enabled, pct_enabled} <- {:pct_enabled, check_percentage_gate(gates, item, flag_name)} do
      group_enabled and pct_enabled
    else
      {:flag_active, false} -> false
      {:actor_override, {:halt, is_enabled}} -> is_enabled
    end
  end

  # Boolean gates override all, acting as a master switch
  defp check_boolean_gate(%{boolean: gate}) do
    {:ok, is_enabled} = Gate.enabled?(gate)
    is_enabled
  end

  defp check_boolean_gate(_), do: false

  # Actors override, so if actor is defined we break and return
  defp check_actor_gates(%{actor: gates}, item) when not is_nil(item) do
    Enum.reduce_while(gates, :cont, fn gate, acc ->
      case Gate.enabled?(gate, for: item) do
        {:ok, is_enabled} -> {:halt, {:halt, is_enabled}}
        _ -> acc
      end
    end)
  end

  defp check_actor_gates(_, _), do: :cont

  # If groups are defined and an item is passed, then the item must pass all groups.
  defp check_group_gates(%{group: gates}, item) when not is_nil(item) do
    Enum.reduce_while(gates, true, fn gate, acc ->
      case Gate.enabled?(gate, for: item) do
        {:ok, true} -> {:cont, acc}
        _ -> {:halt, false}
      end
    end)
  end

  # If there is no group defined, or no item, the group is ignored and the gate passes.
  defp check_group_gates(_, _), do: true

  # If % of Actors gate is defined, evaluate.
  defp check_percentage_gate(%{pct_actor: gate}, item, flag_name) when not is_nil(item) do
    {:ok, is_enabled} = Gate.enabled?(gate, for: item, flag_name: flag_name)
    is_enabled
  end

  # If % of Time is defined, and no other patterns match, evaluate.
  defp check_percentage_gate(%{pct_time: gate}, _, _) do
    {:ok, is_enabled} = Gate.enabled?(gate)
    is_enabled
  end

  # If no matches are found, ignore and pass the gate
  defp check_percentage_gate(_, _, _), do: true

  defp gates_by_type(gates) do
    gates =
      Enum.group_by(
        gates,
        fn gate ->
          cond do
            Gate.boolean?(gate) -> :boolean
            Gate.actor?(gate) -> :actor
            Gate.group?(gate) -> :group
            Gate.percentage_of_time?(gate) -> :pct_time
            Gate.percentage_of_actors?(gate) -> :pct_actor
          end
        end
      )

    gates = if gates[:boolean], do: Map.put(gates, :boolean, List.first(gates.boolean)), else: gates
    gates = if gates[:pct_time], do: Map.put(gates, :pct_time, List.first(gates.pct_time)), else: gates
    if gates[:pct_actor], do: Map.put(gates, :pct_actor, List.first(gates.pct_actor)), else: gates
  end
end
```

**Comment by tompave** [comment]
Hi @erikreedstrom, I'm glad you've found something that works for your use case. 👍 

The gate precedence and combination rules you've implemented are quite different from how the library work, but it's cool that you can at least leverage the other underlying features.

> The Boolean gate works as a master switch;

This is actually interesting. I think it's too far away from how boolean gates are used in the lib, but I can see why it would be useful.
The way I'd achieve the same it by using two different flags to be honest, but I understand that it's not something that would work in your project.

Well, thanks for the suggestions! :-)
