### ISSUE TITLE
[Question] How to toggle flag in production?

### ISSUE THREAD

**Issue by jlurena** [tompave/fun_with_flags#39]
Production servers in my scenario cannot run iex, so DevOps can't toggle the feature flags using the functions described in the documentation. 

In essence, my question is, will toggling the flag in Redis store have the desired effect with compiled code?

**Comment by jlurena** [comment]
To answer my own question, it does.

**Comment by tompave** [comment]
Hey, hi @jlurena,

thank you for trying the package and I'm glad that you sorted that out.

Just one thing:

> my question is, will toggling the flag in Redis store have the desired effect with compiled code?
> (...)
> To answer my own question, it does.

Do you mean that you're writing directly into the Redis instance?

Well, yes, that will work, but it's really not advisable because:

1. It can be difficult to issue the right Redis commands, especially with complex flags and gates. Several operations actually require multiple commands, to be executed together with a [`MULTI`](https://redis.io/commands/multi), and there is a risk to write either the wrong data or incomplete data.
2. Even if you do it right it won't invalidate the caches, so your nodes will have to wait for any cached content to expire before any change written directly to Redis will become available. You _could_ also directly issue the Redis commands to broadcast the change notifications (if using the Redis PubSub adapter), but then the considerations of point 1 still apply.
3. You should really not interact with datastores directly in production, although I guess that your Ops team knows what they're doing.

> Production servers in my scenario cannot run iex, so DevOps can't toggle the feature flags using the functions described in the documentation.

The public functions, from the readme and the documentation, don't need to be run in `IEx`. The examples in the docs show sequences of commands to showcase the capabilities of the package, but it's unlikely that you'd do the same in production.

You have two choices:

1. Wrap the flag changes with some function that you control, for example something triggered by an HTTP request.
2. Use the web UI plugin: https://github.com/tompave/fun_with_flags_ui
