### ISSUE TITLE
'conflict_target' in Ecto persistence prevents use with MySQL

### ISSUE THREAD

**Issue by stewart** [tompave/fun_with_flags#40]
Howdy! I'm attempting to integrate `fun_with_flags` into a Phoenix app that's using a MySQL database. Unfortunately, at the moment it doesn't quite behave as expected:

```
iex(1)> FunWithFlags.enable(:test_flag)
** (ArgumentError) The :conflict_target option is not supported in insert/insert_all by MySQL
    (ecto_sql) lib/ecto/adapters/mysql/connection.ex:972: Ecto.Adapters.MySQL.Connection.error!/2
    (ecto_sql) lib/ecto/adapters/mysql/connection.ex:149: Ecto.Adapters.MySQL.Connection.insert/6
    (ecto_sql) lib/ecto/adapters/mysql.ex:208: Ecto.Adapters.MySQL.insert/6
    (ecto) lib/ecto/repo/schema.ex:651: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:264: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
    (fun_with_flags) lib/fun_with_flags/store/persistent/ecto.ex:193: FunWithFlags.Store.Persistent.Ecto.do_insert/3
    (fun_with_flags) lib/fun_with_flags/store/persistent/ecto.ex:71: FunWithFlags.Store.Persistent.Ecto.put/2
    (fun_with_flags) lib/fun_with_flags/store.ex:36: FunWithFlags.Store.put/2
    (fun_with_flags) lib/fun_with_flags.ex:185: FunWithFlags.enable/2
```

It should be possible to add this option to the insert statement dynamically, based on the result of `Repo.__adapter__` (AFAIK, MySQL is the special case here) - but I'm not certain if that's the best way to approach this.

If you'd welcome a patch implementing the above suggestion, let me know.

**Comment by tompave** [comment]
Hello! 👋 

Thank you for trying the library and for raising the issue.

I see. Unfortunately I've developed using Postgres locally, and I've never tested it with MySQL. I just assumed that Ecto's API and its options would work with any RDBMS supported by the `ecto` package (and, today, the `ecto_sql` package).

It seems that that was naive on my part.

> It should be possible to add this option to the insert statement dynamically, based on the result of Repo.__adapter__ (AFAIK, MySQL is the special case here)

I don't think that's the right way to go about this, because the `on_conflict` and `conflict_target` are used to do an [UPSERT](https://en.wikipedia.org/wiki/Merge_(SQL)#upsert), and removing those for MySQL would resolve this immediate problem but introduce a new one. Doing an UPSERT is required because when you try to create a new flag or modify an existing one, the same persistence adapter function is used. In the case of the ecto adapter, it does an UPSERT.

I suppose we could try to use an approach similar to [the way the percentage gates are set](https://github.com/tompave/fun_with_flags/blob/v1.2.1/lib/fun_with_flags/store/persistent/ecto.ex#L32-L61), which uses a lock and a transaction. It could work, but first I want to check if there is a different way to do an UPSERT in MySQL that doesn't require locking the table.

**Comment by stewart** [comment]
My understanding is that the MySQL adapter uses [`ON DUPLICATE KEY UPDATE`](https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html) to perform upsert operations, and MySQL will detect conflicts automatically (by checking both the primary key and all unique indexes on the table).

As the `fun_with_flags_toggles` table only has a single unique index, I believe the behaviour for MySQL should be identical to Postgres with this proposed change.

**Comment by tompave** [comment]
Reading [the Ecto docs for upserts](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts).

I see, I think you're right. I'd be happy to accept a PR for this. 👍 

The current unit and integration tests should already cover the correctness of the UPSERT behaviour, both with Ecto and Redix.

We'll have to also add a couple of tasks to `.travis.yml` to run the Ecto tests with MySQL.

**Comment by tompave** [comment]
I'd like to continue tracking this work on https://github.com/tompave/fun_with_flags/pull/42.
I'm closing this issue as that specific problem is resolved, and thank you for working on this!
