### ISSUE TITLE
v1.4.0 release date?

### ISSUE THREAD

**Issue by jpserra** [tompave/fun_with_flags#44]
Hello @tompave 

Is v1.4.0 going to be released soon(ish)?
 I really like the changes you introduced with the behavior for `Persistance` that allows to create custom adapters, curious if it's going to be available in the upcoming days to try it out.

**Comment by tompave** [comment]
Hey, hi, thanks. I'm glad that the latest changes will be useful.

Technically you can already try it out on the master branch.

The only thing left is updating some integration tests for the persistence adapters. They're failing not because of broken behaviour, but because they assert on logic that has been moved somewhere else. I hope to get to fix them soonish, but I haven't had much time to spend on this project recently.

**Comment by tompave** [comment]
Everything is now on master, if you want to try it @jpserra .

**Comment by tompave** [comment]
Released.
