### ISSUE TITLE
Is there any reason flag names must be atoms instead of strings?

### ISSUE THREAD

**Issue by smaximov** [tompave/fun_with_flags#51]
The only benefits of atom names I can come up with are [slightly faster comparison](https://github.com/devonestes/fast-elixir#comparing-strings-vs-atoms-code) and less memory usage, but I don't think they would make a considerable difference for a real app. And I didn't even take into account that flag names are already converted to strings (and vice versa) by persistence adapters.

The issues with atom names arise when considering flag names that come from external input (suppose I want to provide this library to non-elixir services by wrapping it in JSON API). Because we cannot just convert arbitrary strings to atoms, it would require using `String.to_existing_atom/1` and rescuing from exceptions in case the flag name does not exist ([as you already do in the web UI](https://github.com/tompave/fun_with_flags_ui/blob/47f657c8d2a022b6c8b7c2894187a8a8a5905980/lib/fun_with_flags/ui/utils.ex#L151-L158)).

**Comment by tompave** [comment]
Hey, hi, thank you for using the library.

My main reasons to use atoms were:

1. Atoms are a bit more lightweight and faster than binaries, and I like to use atoms in my code for things like identifiers.
2. My main use of this library (or [its Ruby inspiration](https://github.com/tompave/fun_with_flags#origin)), and what I've seen other do in the wild, is to first ship code that references a flag, and then create the flag. This means that atoms would already exist in the VM when they're created, being hardcoded in some `FunWithFlags.enabled?(:my_atom)` call, somewhere.
3. Something else that I can't quite remember right now.

This second assumption was a bit naive, and you could say that I used atoms instead of binaries because back then I didn't foresee it would cause issues. Today I agree that binaries would be better, and I've already [allowed binaries as group names](https://github.com/tompave/fun_with_flags/pull/13) in [v0.10.0](https://github.com/tompave/fun_with_flags/blob/master/CHANGELOG.md#v0100). (being a 0.x release, this king of breaking changes were ok-ish)

I could update the library to prefer binaries for the flag names, but there are a few things to consider. First off, it would be a significant breaking change (think about the typespecs), and it would be important to ensure retro-compatibility with using atoms for the flag names. I'm not quite sure if it's something that can be released as a minor version bump on 1.x or if it needs to go into 2.0. I'd also like to benchmark it. I think the gained safety would justify some drop in performance, if it's even noticeable, but it would be good to know if it's there.

> when considering flag names that come from external input (suppose I want to provide this library to non-elixir services by wrapping it in JSON API).

That's a use case that I didn't initially consider, but I can see how it makes sense. If the risk of memory bloat (clients creating lots of random atoms?) is a concern to you, then you could enforce some form of rate limiting to the API. For example, a client could only be allowed to create X flags per minute.

**Comment by smaximov** [comment]
Thanks for the detailed answer!

> I could update the library to prefer binaries for the flag names, but there are a few things to consider. First off, it would be a significant breaking change (think about the typespecs), and it would be important to ensure retro-compatibility with using atoms for the flag names. I'm not quite sure if it's something that can be released as a minor version bump on 1.x or if it needs to go into 2.0.

That's an important concern, but I believe it's possible to add support for binaries as flag names without breaking backward compatibility (I didn't thoroughly read the code so I may be wrong). `enable/2`, `disable/2`, `enabled/2`, and `clear/2` should be straightforward and safe &mdash; add new clauses for binary flag names and soft-deprecate old clauses.

The rest of the API (`all_flag_names/0`, `all_flags/0`, `get_flag/1`) is harder because we cannot overload on the return type. I see two possible solutions:

* Don't do anything (at least for now?). This would create asymmetry in the API so I don't like this solution. 
* Introduce new functions (e.g., `list_flag_names/0`, `list_flags/0`, `flag/1`) that behave like the old ones but return binaries/flags with binary names. Soft-deprecate old functions.

WDYT?

> I'd also like to benchmark it. I think the gained safety would justify some drop in performance, if it's even noticeable, but it would be good to know if it's there.

I completely agree.

**Comment by smaximov** [comment]
> If the risk of memory bloat (clients creating lots of random atoms?) is a concern to you, then you could enforce some form of rate limiting to the API

To be honest, I don't currently have a problem, the example I described is purely hypothetical. It's just a question that came to my mind after looking at the API and the source code.

**Comment by tompave** [comment]
> (...) enable/2, disable/2, enabled/2, and clear/2 should be straightforward and safe — add new clauses for binary flag names and soft-deprecate old clauses.
> 
> The rest of the API (all_flag_names/0, all_flags/0, get_flag/1) is harder because we cannot overload on the return type. I see two possible solutions:
> (...)

Yes, that's a problem too, and that's what makes me think that this kind of change is v2.0 material.
