### ISSUE TITLE
Support for passing in an actor scoring function in configs

### ISSUE THREAD

**Issue by ddresselhaus** [tompave/fun_with_flags#53]
Any thoughts on the ability to pass in an actor scoring function into configs. I'm using a Ruby feature flag lib (rollout) in a different service that uses a different scoring algorithm. It would be nice to have them share the same algorithm.

Something along these lines: https://github.com/SalesLoft/fun_with_flags/pull/1/files
I'm happy to add tests and clean it up.

**Comment by tompave** [comment]
Hi!

Thank you for using the library and for suggesting the feature.

I don't think it's something I'd be open to add at this time, because I think that having an opinionated scoring function and a small set of configuration options makes the library easier to use.

I'll leave this issue open though, to see if anyone else would find it useful. It's something I might consider for version 2.
