### ISSUE TITLE
List of enabled features for an actor

### ISSUE THREAD

**Issue by mustela** [tompave/fun_with_flags#68]
Hello there! 

Im looking for a way to get a list of enabled features by actor, is there any already supported? 

Thanks!

**Comment by mustela** [comment]
I guess I can use `FunWithFlags.all_flags` and then just check each feature...

**Comment by tompave** [comment]
Hi, thank you for using the library.

There is no builtin way to query the list of enabled feature flags for an actor. The reason is that there is no guarantee that the data is stored in a way that makes that selection easy.

For example, with the Redis persistence adapter each flag is stored in a [hash](https://redis.io/topics/data-types#hashes), and there is no way to directly select the hashes that contain a key [with a specific structure](https://github.com/tompave/fun_with_flags/blob/v1.4.1/lib/fun_with_flags/store/serializer/redis.ex#L15). The only way is to iterate the flags and call `HGETALL` on each hash. That's how `FunWithFlags.all_flags/1` works when using Redis.

Things are a bit easier when using the Ecto adapter, as the flags are in a table that you can query directly, if you want. For example:

```sql
select flag_name
from fun_with_flags_toggles
where gate_type = 'actor'
and target = 'your actor ID'
and enabled = true
;
```

Please be aware that the table is not meant to be queried directly, and that it just happens to be structured in a way that makes that query easy. Even though the table schema is not likely to change at this point, that schema is not really part of the public API of the package, and I discourage to access it directly.

> I guess I can use FunWithFlags.all_flags and then just check each feature.

That would be my recommendation, yes.

**Comment by tompave** [comment]
Out of curiosity, why do you need to query that data? What's your use case?

**Comment by mustela** [comment]
Thanks A LOT for taking the time to answer with so much details. I really appreciate it. 

The use case, is because this is an API and I have two clients, a mobile app and a web app. Both need to know which features the logged in user has enabled in order to hide/show experimental features.

**Comment by tompave** [comment]
@mustela I see.

Then if the query has to be performed relatively frequently, I'd strongly recommend caching the results somehow. `FunWithFlags.all_flags/0` bypasses the ETS cache (because the cache might not contain all the data), and it goes directly to the persistence layer. Performing those queries too often might significantly increase the load.

**Comment by mustela** [comment]
Great, will do that. Thanks again!
