### ISSUE TITLE
In memory store

### ISSUE THREAD

**Issue by tomtaylor** [tompave/fun_with_flags#78]
I was previously using the [`fun_with_flags_in_memory`](https://hex.pm/packages/fun_with_flags_in_memory) library for getting/setting feature flags in our test environment. The repo now seem to have been deleted, and the package isn't compatible with 1.5 as it depends on 1.4.0. Would it make sense to bring this store into the main library, explicitly for people unit testing? If not, is there another preferred option for this use case?

**Comment by tomtaylor** [comment]
Apologies - the repo hasn't been deleted - the wrong link is set in the package. The correct link is: https://github.com/naps62/fun_with_flags_in_memory

I guess my question still stands though - should we bring this into the main library?

**Comment by tompave** [comment]
Hello, and thank you for using the library.

That package originally comes from this PR: https://github.com/tompave/fun_with_flags/pull/50. I didn't want to include that adapter in the library, and I suggested that they'd publish it as plugin package instead, which they did. I'd say that you can send a PR on that repo where you bump the dependency on `fun_with_flags`. (And since you're there, you can fix the broken link 😉)

As to why I didn't want to accept that PR, as I wrote in one of those comments, I just don't think that using an in-memory adapter for the tests is the right thing to do.
